/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmatuskaAmbulanceWlList {
    }
}
declare global {
    interface HTMLXmatuskaAmbulanceWlListElement extends Components.XmatuskaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXmatuskaAmbulanceWlListElement: {
        prototype: HTMLXmatuskaAmbulanceWlListElement;
        new (): HTMLXmatuskaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xmatuska-ambulance-wl-list": HTMLXmatuskaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XmatuskaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xmatuska-ambulance-wl-list": XmatuskaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmatuska-ambulance-wl-list": LocalJSX.XmatuskaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXmatuskaAmbulanceWlListElement>;
        }
    }
}
